# fly.toml app configuration file generated for beverage-reviews on 2024-03-26T18:08:15+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'beverage-reviews'
primary_region = 'ams'

[build]

[env]
  PORT = "5000"

[[services]]
  internal_port = 5000

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
